home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

learning_django/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^$', include('home.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
	# ex: /polls/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    url(r'^(?P<pk>[0-9]+)/$',
    	views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<pk>[0-9]+)/results/$',
    	views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    # ex: /polls/all/
    url(r'^all/$', views.AllQuestionsView.as_view(), name='all'),
    url(r'^popular/$', views.PopularView.as_view(), name='popular'),
]

home/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

polls/models.py
from __future__ import unicode_literals

import datetime

from django.db import models
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible

# Create your models here.

@python_2_unicode_compatible
class Question(models.Model):
	"""
		The DB model for a poll question
	"""
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')

	def __str__(self):
		return self.question_text

	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now

	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published recently?'


@python_2_unicode_compatible
class Choice(models.Model):
	"""
		The DB model for a possible choice linked to a question
	"""
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __str__(self):
		return self.choice_text

home/views.py
from django.shortcuts import render

def index(request):
	return render(request, 'home/index.html')

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.views import generic
from django.db.models import F, Count, Sum
from django.utils import timezone

from .models import Choice, Question


class IndexView(generic.ListView):
	"""
		Displays a landing page showing the latest 5 poll questions
	"""
	template_name = 'polls/index.html'
	context_object_name = 'latest_question_list'

	def get_queryset(self):
		"""
			Return the last five published questions (not including those
			set to be published in the future or ones without a choice)
		"""
		return Question.objects \
			.annotate(choice_cnt=Count('choice')) \
			.exclude(choice_cnt=0) \
			.filter(pub_date__lte=timezone.now()) \
			.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
	"""
		Shows info for a specific question based on its ID number
	"""
	model = Question
	template_name = 'polls/detail.html'

	def get_queryset(self):
		"""
			Excludes any questions that aren't published yet, and
			any questions without a choice
		"""
		return Question.objects \
			.annotate(choice_cnt=Count('choice')) \
			.exclude(choice_cnt=0) \
			.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
	"""
		Shows results for a specific question based on its ID number
	"""
	model = Question
	template_name = 'polls/results.html'

	def get_queryset(self):
		"""
			Excludes any questions that aren't published yet, and
			any questions without a choice
		"""
		return Question.objects \
			.annotate(choice_cnt=Count('choice')) \
			.exclude(choice_cnt=0) \
			.filter(pub_date__lte=timezone.now())


def vote(request, question_id):
	"""
		Vote on a specific question based on its ID number
	"""
	question = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		# Redisplay the question voting form
		return render(request, 'polls/detail.html',
			{'question': question,
			'error_message': "You didn't select a choice."})
	else:
		selected_choice.votes = F('votes') + 1
		selected_choice.save()
		# Always return an HttpResponseRedirect after successfully dealing
		# with POST data. This prevents data from being posted twice if a
		# user hits the Back button.
		return HttpResponseRedirect(reverse('polls:results',
			args=(question.id,)))


class AllQuestionsView(generic.ListView):
	"""
		Displays a listing showing all poll questions
	"""
	template_name = 'polls/all-questions.html'
	context_object_name = 'full_question_list'

	def get_queryset(self):
		"""
			Return the last five published questions (not including those
			set to be published in the future or ones without a choice)
		"""
		return Question.objects \
			.annotate(choice_cnt=Count('choice')) \
			.exclude(choice_cnt=0) \
			.filter(pub_date__lte=timezone.now()) \
			.order_by('-pub_date')


class PopularView(generic.ListView):
	"""
		Displays a list of the 5 most popular questions
	"""
	template_name = 'polls/popular-questions.html'
	context_object_name = 'popular_question_list'

	def get_queryset(self):
		"""
			Return the five most popular questions based on vote counts
		"""
		return Question.objects \
			.annotate(choice_cnt=Count('choice')) \
			.exclude(choice_cnt=0) \
			.annotate(votes=Sum('choice__votes')) \
			.filter(pub_date__lte=timezone.now()) \
			.order_by('-votes')[:5]

home/templates/home/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Learning Django</title>
</head>
<body>
	<p>There's nothing interesting here.  Check out one of the Django apps:</p>
	<ul>
		<li>
			<a href="http://learning-django.coralvanda.com/polls">Polls app</a>
		</li>
	</ul>
</body>
</html>

polls/templates/polls/all-questions.html
{% extends "polls/base.html" %}
{% block content %}

{% if full_question_list %}
	<ul>
		{% for question in full_question_list %}
			<li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
			</li>
		{% endfor %}
	</ul>
{% else %}
	<p>No polls are available.</p>
{% endif %}

{% endblock %}

polls/templates/polls/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<title>Polls</title>
	{% load static %}
	<link rel="stylesheet" type="text/css"
	href="{% static 'polls/style.css' %}" />
</head>
<body>
	<div id="container">
		{% include "polls/header.html" %}

		{% block content %}
		{% endblock %}
	</div>
</body>
</html>

polls/templates/polls/detail.html
{% extends "polls/base.html" %}
{% block content %}

<h1>{{ question.question_text }}</h1>

{% if error_message %}
	<p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
	{% csrf_token %}
	{% for choice in question.choice_set.all %}
		<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
		<label for="choice{{ forloop.counter }}">
			{{ choice.choice_text }}
		</label><br>
	{% endfor %}
	<input type="submit" name="Vote"/>
</form>

{% endblock %}

polls/templates/polls/header.html
<header>
	Polls - just for fun
</header>

<nav>
	<a href="http://coralvanda.com">
		<div class="button">Home</div>
	</a>
	 <a href="{% url 'polls:index' %}">
	 	<div class="button">Latest Questions</div>
	 </a>
	 <a href="{% url 'polls:all' %}">
	 	<div class="button">All questions</div>
	 </a>
	 <a href="{% url 'polls:popular' %}">
	 	<div class="button">Most popular</div>
	 </a>
</nav>

polls/templates/polls/index.html
{% extends "polls/base.html" %}
{% block content %}

{% if latest_question_list %}
	<ul>
		{% for question in latest_question_list %}
			<li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
			</li>
		{% endfor %}
	</ul>
{% else %}
	<p>No polls are available.</p>
{% endif %}

{% endblock %}

polls/templates/polls/popular-questions.html
{% extends "polls/base.html" %}
{% block content %}

{% if popular_question_list %}
	<ul>
		{% for question in popular_question_list %}
			<li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
			</li>
		{% endfor %}
	</ul>
{% else %}
	<p>No polls are available.</p>
{% endif %}

{% endblock %}

polls/templates/polls/results.html
{% extends "polls/base.html" %}
{% block content %}

<h1>{{ question.question_text }}</h1>

<ul>
	{% for choice in question.choice_set.all %}
		<li>
			{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}
		</li>
	{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

{% endblock %}